### ISSUE TITLE
lelar66's recommendation for things to do/eat

### ISSUE THREAD

**Issue by lelar66** [githubteacher/devs-oct-17#16]
### \-  things to do
- KidSpace in Pasadena
- Huntington Library children's garden
### -eat
- soup plantation

**Comment by al-niessner** [comment]
My favorite part of issues and pull requests is that I can simply
answer via email and do have to use the github UI!
On Mon, 2016-10-17 at 10:47 -0700, lelar66 wrote:

> ##recommendations
> - things to do
>   KidSpace in Pasadena
>   Huntington Library children's garden
>   —
>   You are receiving this because you are subscribed to this thread.
>   Reply to this email directly, view it on GitHub, or mute the thread.
>   -- 
>   Al Niessner

I have never found the companion that was so companionable as solitude.
- From Walden by Henry David Thoreau

The universe is indifferent, and life is brutal; however, it is man's
choice of behavior that makes them malevolent rather than benevolent.

Some will fall in love with life and drink it from a fountain
That is pouring like an avalanche coming down the mountain.
- From the song Pepper by the Butthole Surfers
